### ISSUE TITLE
My Chat box is gone

### ISSUE THREAD

**Issue by angpace** [learn-co-curriculum/phase-0-intro-to-js-2-looping-code-along#9]
### Canvas Link

https://github.com/learn-co-curriculum/phase-0-intro-to-js-2-looping-code-along/issues/new?assignees=&labels=se+curriculum&template=se_report.yml

### Concern

Hello, I need help with a problem and my chat box is gone so I am unable to ask for help. I already refreshed, closed out and quit the page and reopened but it still hasn't appeared.

**Comment by lizbur10** [comment]
Hi @angpace! Chat was closed for the Labor Day holiday - I'm guessing that's why you weren't seeing the chat box. Apologies for the inconvenience!

I'm going to go ahead and close this issue, but if you are still unable to access chat please reopen it 💙
